version: 2

jobs:
  linux:
    docker:
      - image: swift:latest
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: swift:latest
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  linux-nightly-5.2:
    docker:
      - image: swiftlang/swift:nightly-5.2
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-nightly-5.2-release:
    docker:
      - image: swiftlang/swift:nightly-5.2
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev
      - run:
          name: Compile code with optimizations
          command: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
      - linux-nightly-5.2
      - linux-nightly-5.2-release
